= Tan Thong Cai Nelvin - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets
:sectnums:

== PROJECT: One Life

---

=== Overview

One Life is a desktop medical management application used for storing and displaying data related to patients and doctors.
One Life aims to improve the efficiency for administrative processes in medical institutes.
The user interacts with it using a Command Line Interface (CLI), and it has a Graphical User Interface (GUI) created with JavaFX.
It is written in Java, and has about 10 kLoC.

=== Summary of contributions

* *Major enhancement*: added *the ability to schedule and display medical appointments*
** What it does: allows the user to schedule appointments at a specified time.
** Justification: This feature improves the product significantly because a user is able to display current appointments and schedule appointments.
This is a key part of medical operations in a hospital.
Further checks are available to inform the user if they keyed in incorrect appointment details.
** Highlights: This enhancement drastically improved the ability of the application to assist medical processes, specifically in the area of scheduling appointment.
The implementation too was challenging as it required a brand new command to be created.

* *Code contributed*: [https://github.com/CS2103-AY1819S1-W16-3/main/commits?author=nelvintan[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Project management:
*** Managed releases `v1.1` - `v1.4` (4 releases) on GitHub
*** Set up travis for running tests for the code base
*** Set up auto publishing of docs for travis
** Enhancements to existing features:
*** Updated the GUI color scheme (Pull requests https://github.com[#33], https://github.com[#34])
*** Wrote additional tests for existing features to increase coverage%
(Pull requests https://github.com/CS2103-AY1819S1-W16-3/main/pull/11/commits/7203d4a630e46fdf724c76170e3589de7704687d[#36],
https://github.com/CS2103-AY1819S1-W16-3/main/pull/68/commits/ad0a044af6a04de2a7c5d456c4bc5753c60aacd4[#38])
** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide:
https://github.com/CS2103-AY1819S1-W16-3/main/pull/123/commits/a8d665e38c5f07a50f6e38635bcc54b858193ac4[#14]
** Community:
*** PRs reviewed (with non-trivial review comments):
https://github.com/CS2103-AY1819S1-W16-3/main/pull/124#pullrequestreview-169082170[#12],
https://github.com[#32],
https://github.com[#19],
https://github.com[#42]
*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com[1], https://github.com[2], https://github.com[3])

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=displayappt]

include::../UserGuide.adoc[tag=schedule]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=schedulecommand]


== PROJECT: PowerPointLabs

---

_{Optionally, you may include other projects in your portfolio.}_
