= Tan Thong Cai Nelvin - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets
:sectnums:

== PROJECT: One Life

---

=== Overview

This project portfolio details my key contributions to Project One Life.

One Life is a desktop medical management application designed by me and my groups mates for a software engineering module in National University of Singapore (NUS).
It aims to improve the efficiency of administrative processes in medical institutes.
The project was created under the constraint of the fact that the user only interacts with the application through a Command Line Interface (CLI).
It is written in Java, and has about 10 kLoC.

The main features of the project are:

* The ability to display and schedule medical appointments.
* The ability to display and update medical records.
* The ability to display doctor and patient details.
* The ability to find persons by specifying related keywords.
* The ability to enter commands using intuitive command prompts instead of CLI for new users.

=== Summary of Contributions

* *Major enhancement*: added the ability to schedule and display medical appointments.
** What it does: This enhancement allows the user to schedule appointments at a specified time.
** Justification: This feature improves the product significantly because a user is able to display current appointments and schedule appointments.
This is a key part of medical operations in a hospital.
Further checks are available to inform the user if they keyed in incorrect appointment details.
** Highlights: This enhancement drastically improved the ability of the application to assist medical processes, specifically in the area of scheduling appointment.
The implementation too was challenging as it required a brand new command to be created.

* *Minor enhancement*: added the ability to check for valid date and time which is useful for scheduling and updating commands.

* *Code contributed*: [https://github.com/CS2103-AY1819S1-W16-3/main/commits?author=nelvintan[Functional code]] [https://nus-cs2103-ay1819s1.github.io/cs2103-dashboard/#=undefined&search=nelvintan&sort=displayName&since=2018-09-12&until=2018-11-06&timeframe=day&reverse=false&repoSort=true[RepoSense]]

* *Other contributions*:

** Project management:
*** Managed releases `v1.1` - `v1.4` (4 releases) on GitHub.
*** Set up travis for continuous integration of the code base.
*** Set up auto publishing of documentation for travis.
** Enhancements to existing features:
*** Wrote additional tests for existing features to increase coverage %.
(Pull requests https://github.com/CS2103-AY1819S1-W16-3/main/pull/11/commits/7203d4a630e46fdf724c76170e3589de7704687d[#11],
https://github.com/CS2103-AY1819S1-W16-3/main/pull/68/commits/ad0a044af6a04de2a7c5d456c4bc5753c60aacd4[#68])
** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide.
(Pull requests https://github.com/CS2103-AY1819S1-W16-3/main/pull/123/commits/a8d665e38c5f07a50f6e38635bcc54b858193ac4[#123],
https://github.com/CS2103-AY1819S1-W16-3/main/pull/192[#192],
https://github.com/CS2103-AY1819S1-W16-3/main/pull/203[#203])
** Community:
*** Reviewed other team members' pull requests.
(Pull request https://github.com/CS2103-AY1819S1-W16-3/main/pull/124#pullrequestreview-169082170[#124])
*** Reported bugs and suggestions for other teams in the class.
(Pull requests https://github.com/CS2103-AY1819S1-W16-3/main/pull/124#pullrequestreview-169082170[#124],
https://github.com/CS2103-AY1819S1-W16-3/main/pull/204[#204])

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=displayappt]

include::../UserGuide.adoc[tag=schedule]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=schedulecommand]

