= Triston Pang Erh Syen - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets
:sectnums:

== PROJECT: One Life

---

=== Overview

One Life is a desktop medical management application used for storing and displaying data related to patients and doctors.
One Life aims to improve the efficiency for administrative processes in medical institutes.
The user interacts with it using a Command Line Interface (CLI), and it has a Graphical User Interface (GUI) created with JavaFX.
It is written in Java, and has about 10 kLoC.

=== Summary of contributions

* *Major enhancement*: added *the intuitive command prompt functionality*
** What it does: intuitively guides and instructs the user to enter the correct inputs into the
required fields of a command
** Justification: This feature improves the product significantly because new or less tech-saavy users are able to
easily use the product. The step-by-step walkthrough of commands by the intuitive command prompt also simplifies the
typing of commands and can potentially reduce errors.
** Highlights: This enhancement involves all commands that take in one or more arguments.
The implementation of the enhancement required classes that could keep track of arguments and have different prompting
behaviours depending of the type of command to be executed.

* *Minor enhancement*: added command box clear ability and cancellation of intuitive command ability on `ESC` key press.

* *Code contributed*: [https://github.com/CS2103-AY1819S1-W16-3/main/commits?author=tristonpang[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Project management:
*** Managed releases `v1.1` - `v1.4` (4 releases) on GitHub
*** Tagged releases, compiled binary (JAR) files and published releases on GitHub
** Documentation:
*** Updated class diagram for Logic component:

** Community:
*** Reviewed PRs of other team members: https://github.com/CS2103-AY1819S1-W16-3/main/pull/54#issuecomment-428477267

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=intuitivecommandprompt]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=intuitivecommandprompt]


== PROJECT: PowerPointLabs

---

_{Optionally, you may include other projects in your portfolio.}_
